name: dictionary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Structure
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  #UI
  google_fonts: ^2.3.1
  flutter_launcher_icons: ^0.9.2

  #Database
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3

  #Utils
  validatorless: ^1.2.1
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

 
  assets:
    - assets/icons/
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon_background.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"